id: A4BF05450
title: Prayer for the Long Life of Pewar Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:18:15.250938
  last_modified_at: 2022-03-01 01:18:15.250945
